Toil package builder
Introduce a toil[1]-based workflow to automate patch building for
a package.

[1] https://toil.readthedocs.io/

Change-Id: I7e3a11ad95781b8989d24fbf3992dcb49e4c8dba
Signed-off-by: Pavel Boldin <pboldin@cloudlinux.com>

diff --git a/packages/rhel7/glibc/glibc-2.17-55.el7/info b/packages/rhel7/glibc/glibc-2.17-55.el7/info
--- a/packages/rhel7/glibc/glibc-2.17-55.el7/info
+++ b/packages/rhel7/glibc/glibc-2.17-55.el7/info
@@ -72,7 +72,16 @@ _install_originals() {
 }
 
 _run_tests() {
-	export LD_PRELOAD=/libcare/tests/execve/execve.so
+	if test -f $LIBCARE_DIR/execve/execve.so; then
+		LD_PRELOAD=$LIBCARE_DIR/execve/execve.so
+	elif test -f $LIBCARE_DIR/tests/execve/execve.so; then
+		LD_PRELOAD=$LIBCARE_DIR/tests/execve/execve.so
+	else
+		echo "Can't find execve.so required to run tests"
+		exit 1
+	fi
+
+	export LD_PRELOAD
 
 	local ld_linux="$KP_PROJECT_BUILD_DIR/elf/ld*"
 
@@ -110,9 +119,11 @@ kp_patch_test() {
 	rm -f /var/run/libcare.sock
 
 	PATCH_ROOT=/root/${KP_PROJECT_PATCH%.*}
-	/libcare/src/libcare-ctl -v server /var/run/libcare.sock $PATCH_ROOT \
-		>/root/test.log 2>&1 & :
+	$KPATCH_PATH/libcare-ctl -v server /var/run/libcare.sock $PATCH_ROOT \
+		>/data/test.log 2>&1 & :
 	LISTENER_PID=$!
+	sleep 1
+	kill -0 $LISTENER_PID
 
 	pushd $KP_PROJECT_BUILD_DIR
 
@@ -123,11 +134,11 @@ kp_patch_test() {
 
 	popd
 
-	local patched=$(awk '/kpatch_ctl targeting/ { n++ } END { print n }' /root/test.log)
+	local patched=$(awk '/kpatch_ctl targeting/ { n++ } END { print n }' /data/test.log)
 
 	test $patched -ge $executed
 
-	grep -vq 'No patch(es) applicable to' /root/test.log
-	grep 'patch hunk(s) have been successfully applied' /root/test.log \
+	grep -vq 'No patch(es) applicable to' /data/test.log
+	grep 'patch hunk(s) have been successfully applied' /data/test.log \
 		| wc -l
 }
diff --git a/scripts/pkgbuild b/scripts/pkgbuild
--- a/scripts/pkgbuild
+++ b/scripts/pkgbuild
@@ -54,8 +54,9 @@ prepare() {
 
 	# Export env vars that are needed during the build
 	SCRIPTS="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
-	SPWD="$(realpath $SCRIPTS/../)"
-	export KPATCH_PATH=$SPWD/src
+	LIBCARE_DIR="${LIBCARE_DIR:-$SCRIPTS/..}"
+	KPATCH_PATH="${KPATCH_PATH:-$LIBCARE_DIR/src}"
+	export LIBCARE_DIR KPATCH_PATH
 	export OLDPATH=$PATH
 	export KPATCH_PASSTHROUGH_ASM=1
 	CPUS=`cat /proc/cpuinfo | grep ^processor | wc -l`
@@ -130,18 +131,20 @@ kp_prepare_source_deb() {
 }
 
 kp_prepare_source() {
-	echo "  downloading source for $KP_PROJECT"
-	kp_download_source_$KP_PROJECT_FORMAT
+	if ! test -f /kcdata/$KP_PROJECT_SOURCE; then
+		echo "  downloading source for $KP_PROJECT"
+		kp_download_source_$KP_PROJECT_FORMAT
+	fi
 	echo "  preparing source for $KP_PROJECT"
 	kp_prepare_source_$KP_PROJECT_FORMAT
 }
 
 kp_patch_source() {
 	echo "  patching project"
-	PATCH_DIR=$SPWD/patches
+	PATCH_DIR=$LIBCARE_DIR/patches
 	#patch_list_apply requires this dir
 	mkdir -p /tmp/build.kpatch
-	$SPWD/scripts/patch_list_apply $KP_PROJECT_DIR $PDIR/plist $PATCH_DIR
+	$SCRIPTS/patch_list_apply $KP_PROJECT_DIR $PDIR/plist $PATCH_DIR
 }
 
 kp_prebuild_rpm() {
@@ -364,10 +367,10 @@ overwrite_utils() {
 	TMPBIN=$(mktemp -d --tmpdir)
 
 	mkdir $TMPBIN/bin
-	ln -fs /libcare/src/libcare-cc $TMPBIN/gcc
-	ln -fs /libcare/src/libcare-cc $TMPBIN/cc
-	ln -fs /libcare/src/libcare-cc $TMPBIN/g++
-	ln -fs /libcare/src/libcare-cc $TMPBIN/c++
+	ln -fs $KPATCH_PATH/libcare-cc $TMPBIN/gcc
+	ln -fs $KPATCH_PATH/libcare-cc $TMPBIN/cc
+	ln -fs $KPATCH_PATH/libcare-cc $TMPBIN/g++
+	ln -fs $KPATCH_PATH/libcare-cc $TMPBIN/c++
 	if ! test -x /usr/bin/g++; then
 		rm -f $TMPBIN/g++
 	fi
@@ -379,6 +382,11 @@ overwrite_utils() {
 	fi
 
 	export PATH=$TMPBIN:$PATH
+
+	if test "$(command -v cc)" != "$TMPBIN/cc"; then
+		echo "Can't install our wrappers, missing?"
+		exit 1
+	fi
 }
 
 kp_patch_test() {
